### ISSUE TITLE
New `Conversation` object real-time update at `subscribe` function

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#101]
Following the proposal at SkygearIO/features#66

The `subscribe` function currently return the "old" `Conversation` object, and it's `event_type` is always `update`.

After #102, we should update the "new" `Conversation` object changes in `subscribe` function.

```
{
  "record_type": "conversation",
  "event_type": "create",
  "record": recordObj,
  "original_record": nulll
}
```

event_type should mean:

* `create`: when users is added to a conversation
* `delete`: when users was removed from a conversation
* `update`: when one of the `Conversation` and `UserConversation` DB table's attributes was updated if user participates in the conversation

**Comment by rickmak** [comment]
Close via https://github.com/SkygearIO/chat/pull/99
