### ISSUE TITLE
Provided SDK function for querying recipient on a message

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#107]
For displaying a WhatsApp like message info with delivery info.

**Comment by howawong** [comment]
`chat:get_receipt` lambda is already implemented in plugin. Both Android and iOS SDK has the function hook, but JS SDK does not support at this moment.

**Comment by howawong** [comment]
JS, Android and iOS SDKs support `chat:get_receipt` now, closing this issue.
