### ISSUE TITLE
Remove one from participant don't remove him from admin

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#122]
The original documented behaviour prior https://github.com/SkygearIO/chat/pull/119 is to remove user from admin too.

**Comment by rickmak** [comment]
@howawong I think it is done?

**Comment by carmenlau** [comment]
Currently user will be remove from participant, but he still has admin role in the room. Should remove his admin role in this case

**Comment by howawong** [comment]
@rickmak  I just verified and it is done already.
