### ISSUE TITLE
Design and document how an SDK should send a photo as message attachment

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#140]
It will blocking following issue.

Android - https://github.com/SkygearIO/chat-SDK-Android/issues/51
 iOS- https://github.com/SkygearIO/chat-SDK-iOS/issues/63

I assume the web can be displayed by making an `img` tag with `src` set to the attchement url.

**Comment by carmenlau** [comment]
- Convert image to JPG, downsize the image to max width or height to 1600px. The result image should be round ~3xxkb size. For png, use white background
- Retain the exif data for downsized image

**Comment by rickmak** [comment]
How the SDK determine the message is image/text? The Same question apply to https://github.com/SkygearIO/chat/issues/141

**Comment by Steven-Chan** [comment]
Result of offline discussion:

Save base64 encoded image or video thumbnail in metadata, with key `thumbnail`.

This model can speed up thumbnail rendering and have a more flexible model that can treat different type of preview in other form.

**Comment by carmenlau** [comment]
@rickmak Determine by the content type of attachment?

**Comment by carmenlau** [comment]
The meta data of image

```
{
    "thumbnail": <base64 encoded image string>,
    "height":  1200,
    "width":  1600
}
```
