### ISSUE TITLE
Design and document how an SDK should send a Voice/Audio as message attachment

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#141]
Android - https://github.com/SkygearIO/chat-SDK-Android/issues/50
iSO - https://github.com/SkygearIO/chat-SDK-iOS/issues/64

I think we need to choose a media format that can support in web too.

Even better, we can design a way to making asset set that the targeting platform can pick the format it support.

**Comment by carmenlau** [comment]
- Audio in format `ogg`
- Meta data: soundtrack length

**Comment by rickmak** [comment]
How will the metadata save? I would propose to save as `track-len` at jsonb field `metadata` at message.

**Comment by howawong** [comment]
@rickmak  seems IOS audio recorder does not support ogg.

[Core Audio Format Specification](https://developer.apple.com/library/content/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html)


```objectivec
enum {
kAudioFormatLinearPCM      = 'lpcm',
kAudioFormatAppleIMA4      = 'ima4',
kAudioFormatMPEG4AAC       = 'aac ',
kAudioFormatMACE3          = 'MAC3',
kAudioFormatMACE6          = 'MAC6',
kAudioFormatULaw           = 'ulaw',
kAudioFormatALaw           = 'alaw',
kAudioFormatMPEGLayer1     = '.mp1',
kAudioFormatMPEGLayer2     = '.mp2',
kAudioFormatMPEGLayer3     = '.mp3',
kAudioFormatAppleLossless  = 'alac'
};
```

**Comment by carmenlau** [comment]
After discussion as iOS doesn't have native support to ogg format. We decided to choose m4a format instead. Since the message type will determine by the mime type of asset, and SDK only set assets mime type by extension. So please make sure we set the mime type correctly in uikit (Update the SDK implementation or set in manually).

**Comment by chpapa** [comment]
@rickmak @carmenlau @howawong actually the "design and document" here meant we will have helper function in the SDK to support sending voice / audio message?  (Just asking, I think it make sense)

**Comment by rickmak** [comment]
We will use `ACC` for maximum capability. The mimeType will be `audio/mp4` (refs: https://voice.firefallpro.com/2012/03/html5-audio-video-mime-types.html)

**Comment by rickmak** [comment]
> the "design and document" here meant we will have helper function in the SDK

I think here is to make sure all SDKs are working in the same way, not related to coding. It will make sure Audio uploaded at android will able to load in web/iOS

**Comment by chpapa** [comment]
@rickmak oh I am a bit confused... if it is not related with coding. how the plug-ins / SDK ensure audio uploaded will be ACC?

**Comment by carmenlau** [comment]
Since when the app start or stop recording, how is the message display and the audio play are closely related to the UI. So I thought the recording logic should also be part of the UIKit. UIKit will use existing SDK function to save audio into the message record. 

This issue is to discuss and confirm the audio format (record from uikit) and also the message record format (meta data).

Of course if we find any parts we can move from uikit to sdk, it is good :)

**Comment by chpapa** [comment]
@rickmak @carmenlau so this issue should be in UIKit?

Actually I'm skeptical if everything is closely related to the UI. I guess there could be some utility function in the SDK, and not sure if they are really UI related.

For example, something like that below could encapsulate a lot of code for users in different platform, but still able to works with different UI?

Core API:
`sendMessageWithAudio(message, audiofile)`

Utility Functions:
`initAudioRecording()`
`recordingStart()`
`recordingPause()`
`recordingStop()`
`setRecordFinishCallBack(func)`
`playRecording()`

Other thought:
* I felt like this case is similar to UserTypingIndicator in chat 
* If our UIKit is so flexible that we determine 95% of the users should just use it, we can combine utility functions to UIKit too.
* Maybe it would be easier to implement the UIKit first and then extract the code and refactor them to the API too.

**Comment by chpapa** [comment]
I think this is done, but there are not utility functions for those who don't use UIKit? Created #157 for it.

**Comment by rickmak** [comment]
@carmenlau I think it should result in the written documentation at https://github.com/SkygearIO/chat/tree/master/doc ?

**Comment by carmenlau** [comment]
@rickmak Just submitted a PR for that! Thanks :)
