### ISSUE TITLE
Should provide the existing conversation id in error, when user createConversation with `DISTINCT_BY_PARTICIPANTS` 

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat#150]
May need updates for the SDK

Currently when user createConversation with `DISTINCT_BY_PARTICIPANTS`. If there is existing conversation, function will throw error. In the normal case, user will want to know the existing conversation and enter the conversation view

**Comment by arsewizz** [comment]
Hi guys, when are we going to see this feature in place?

**Comment by carmenlau** [comment]
@arsewizz The feature was merged to master already. If you are using your own cloud code, you can checkout the latest master to try the feature. For the skygear cloud plugin release, it is still under testing. May release probably next week.

**Comment by arsewizz** [comment]
I can wait, a question !!! in case I find an existing conversation how to be redirected to it

**Comment by carmenlau** [comment]
@arsewizz When you call `createConversation` with `DISTINCT_BY_PARTICIPANTS`, the behavior will be the same. But there will be `conversation_id` in the error info, you can use `getConversation` api to get back the conversation object by id.

This is an example of android.
https://github.com/skygear-demo/android-chat-uikit-demo/commit/00df43269b8b283ecda54110a83bddfb156bd460

**Comment by arsewizz** [comment]
and we who use javascript, especially ionic 2 !!!

**Comment by arsewizz** [comment]
any update ?

**Comment by carmenlau** [comment]
@arsewizz The fix is live in cloud!

In js, when you call `createConversation` with `DISTINCT_BY_PARTICIPANTS`, you will see following error if there is existing chat. You can retrieve the conversation id from the info.

```
{
    "error": {
        "code": 108,
        "info": {
            "conversation_id": "<conversation_id>"
        },
        "message": "Conversation with the participants already exists",
        "name": "InvalidArgument"
    },
    "status": 400
}
```

**Comment by arsewizz** [comment]
I have the same mistake, not the same as you! what to do ?

**Comment by arsewizz** [comment]
thank you for the assistance, I solve the problem. thank you
