### ISSUE TITLE
Hooks for Cloud Functions

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#158]
Would be useful for Push Notification support. So the following are model around push notification.

* Messages
  * after_message_sent
  * after_message_updated
  * after_message_deleted
* Typing
  * typing_started
* Conversation
  * after_conversation_created (direct / normal)
  * after_conversation_deleted
  * after_conversation_updated
  * after_user_entered_conversation (user / admin)
  * after_user_leave_conversation

**Comment by howawong** [comment]
Hey, what about user created and deleted?

**Comment by chpapa** [comment]
> Hey, what about user created and deleted?

I think these are good Cloud Functions hook. Actually, there is one feature issue about it: https://github.com/SkygearIO/features/issues/101

But I just didn't know normal apps will send a push notification when user sign up or deleted.

If you think when you work on this issue, it is easy for you to just add other cloud functions hook, feel free to do so.

Or did you meant something else?

**Comment by carmenlau** [comment]
Missing parameter for the hook, need updating the spec

**Comment by arsewizz** [comment]
glad that this issue's solved, eager to work on this

**Comment by rickmak** [comment]
Current implementation is not capable to have multiple hooks of the same type.

**Comment by rickmak** [comment]
To be follow up at https://github.com/SkygearIO/chat/issues/182
