### ISSUE TITLE
Sample code for sending push notification

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat#168]
The expected result should user only need to copy the code, use skycli init and deploy. The plugin will be able to send push notification.

**Comment by carmenlau** [comment]
Guides under cloud function

**Comment by carmenlau** [comment]
The repos for the sample cloud function
https://github.com/skygear-demo/cloud-chat-demo-js
https://github.com/skygear-demo/cloud-chat-demo-py

**Comment by howawong** [comment]
Code updated to both repo.
