### ISSUE TITLE
Missing data migration when upgrading schema from 0.24

### ISSUE THREAD

**Issue by wallacesky** [SkygearIO/chat#178]
## Issue
After upgrading from 0.24 to the latest commit fdd2bcd, all chat related tables and columns had been altered. However, data migration is missing after columns' names changed. For example, `conversation_id` -> `conversation` in `message` table. This leads to some unexpected query results.

## Expected Behaviour 
Do data migration before chat plugin is initialised

**Comment by rickmak** [comment]
Won't fix for now.
