### ISSUE TITLE
Return undefined operation after message sent

### ISSUE THREAD

**Issue by wallacesky** [SkygearIO/chat#179]
## Environment
skygear server -> `1.1.3`
chat plugin -> fdd2bcd
chat SDK iOS -> [304908f](https://github.com/SkygearIO/chat-SDK-iOS/commit/304908fbf20e139c064c70aa9105b886d8d8fe0e)

## Issue
Steps
1. Send a new message from iOS client SDK 
2. This message record could be saved properly in database with proper values.
3. After a message sent from iOS SDK, server returns `UndefinedOperation` error which indicated to the action of `chat:after_message_sent_hook`
4. `conversation` record didn't updated `last_message` field with the new message id accordingly

The error logs is attached below
[after_message_sent_hook_error.txt](https://github.com/SkygearIO/chat/files/1498318/after_message_sent_hook_error.txt)

**Comment by wallacesky** [comment]
Problem should be solved.

I checkout the latest code of `chat` plugin with `skygear-server` `v1.1.3` and built with `docker`.
The chat plugin works properly without returning any error.
Also, the `last_message` field is able to refer to the message table

My issue about returning `UndefinedOperation` maybe due to the different `docker` environment variables values in my `docker-compose.yml`.

Sorry for those mistake I've made, thanks for help !

**Comment by rickmak** [comment]
What is your version of py-skygear? I think it is related to this issue after looking at it: https://github.com/SkygearIO/py-skygear/pull/171

So probably upgrade to head will make http/zmq behave the same.

**Comment by wallacesky** [comment]
I used `py-skygear:v1.1.1`
Thanks, I will give it a try

**Comment by wallacesky** [comment]
Still not working. logs here: https://gist.github.com/wallacesky/d18e0a43b105856061789d26469d05d6

**Comment by rickmak** [comment]
Verified the bug is resolved upstead at py-skyegar:v1.1.1
