### ISSUE TITLE
Return undefined operation after conversation created

### ISSUE THREAD

**Issue by wallacesky** [SkygearIO/chat#180]
## Environment
skygear server -> `1.1.3`
chat plugin -> fdd2bcd
chat SDK iOS -> [304908f](https://github.com/SkygearIO/chat-SDK-iOS/commit/304908fbf20e139c064c70aa9105b886d8d8fe0e)

## Issue
Steps
1. Signup or login with Skygear SDK
2. Call `createDirectConversationWithUserID()` in iOS client SDK
3. The new `conversation` record could be inserted in database, however, the fields of `admin_ids`, `participant_ids` and `participant_ids` are remaining `NULL` values
4. Server returns `UndefinedOperation` error which indicated to the action of `chat:after_conversation_created_hook`

The error logs is attached below
[after_conversation_create_hook_error.txt](https://github.com/SkygearIO/chat/files/1498336/after_conversation_create_hook_error.txt)

**Comment by wallacesky** [comment]
Problems solved 
details: https://github.com/SkygearIO/chat/issues/179#issuecomment-347014144

**Comment by howawong** [comment]
@carmenlau  close it?

**Comment by rickmak** [comment]
Verified the bug is resolved upstead at py-skyegar:v1.1.1
