### ISSUE TITLE
Subscribe to a conversation failed occasionally

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat#204]
Some time subscribe to a conversation failed. It looks like if all messages in a room are marked as read, subscribe to conversation doesn’t work. Not 100% sure. Need verify.

Reported user is using JS SDK in hybrid app.

**Comment by carmenlau** [comment]
Need further check the following scenario

- JS 
    - Does the SDK support reconnect
    - Check reconnection in react native 

- iOS and Android 
    - Check the reconnection when user leave and re-enter the app in different situations (phone sleep and on, switch between apps)

**Comment by carmenlau** [comment]
@howawong Would like to know any findings or updates so far? About JS reconnect and the reconnection in react native. Thanks!!

**Comment by howawong** [comment]
talked to @chpapa last friday. I think it is the expected behavior of pubsub as it is not expected to receive any message sent from plugin after the connection is lost and even the connection is recovered. I think we either have

1. persistent pubsub or 
2. call `getMessages` in pubsub listener `onOpen` in UIKit

The first approach is probably too big for now, I think we can stick to the second approach.

**Comment by howawong** [comment]
and @chpapa found the issue in Android/ iOS

**Comment by howawong** [comment]
@carmenlau  I had verified with chat-SDK-JS demo, the reconnection works as expected.

**Comment by howawong** [comment]
Further tested with react native sample code, the reconnection still works after switching different apps, turning off screen and airplane mode.

**Comment by howawong** [comment]
@carmenlau , @chpapa 
As discussed, the pub/sub is not persistent. Therefore it is best to call `getMessages()` whether pub/sub connection is established.

Sample Code
```javascript
function refresh() {
  skygearChat.getMessages(conversation, limit, beforeTime)
    .then(function (messages) {
       //Update the UI with new messages
    });
}

const refreshHandler = skygear.pubsub.onOpen(refresh);
```
Meanwhile, there is an issue regarding  pub/sub SkygearIO/skygear-server#556.

**Comment by carmenlau** [comment]
Check the client app, it looks like it is not related to the connection status. The user never get any message after enter the room, for the room has around 200 people.
