### ISSUE TITLE
The data structure of objects in getMessages and object return by createMessage is inconsistent

### ISSUE THREAD

**Issue by chankiyu22** [SkygearIO/chat#33]
The generic fields are named differently.

In response of getMessages:
![screen shot 2016-09-08 at 3 59 58 pm](https://cloud.githubusercontent.com/assets/3663179/18341644/85823406-75dd-11e6-9ee9-52a2a629937c.png)

Snippet to reproduce the above result:

``` js
skygear_chat.getMessages(conversationId)
.then(function (messages) {
  console.log('Plugin get messages success', messages);
});
```

In response of createMessage:
![screen shot 2016-09-08 at 4 00 36 pm](https://cloud.githubusercontent.com/assets/3663179/18341648/8f3ad9e4-75dd-11e6-8c16-8876953d2360.png)

Snippet to reproduce the above result:

``` js
skygear_chat.createMessage(conversationId, body)
.then(function (message) {
  console.log('Create message success', message);
});
```

**Comment by chankiyu22** [comment]
And the message object published by skygear chat subscribe function has different data structure from createMessage too.
![screen shot 2016-09-08 at 4 13 28 pm](https://cloud.githubusercontent.com/assets/3663179/18342039/84b6c2ec-75df-11e6-94dd-b16dee9f5266.png)

Snippet to reproduce the above result:

```js
skygear_chat.subscribe(function (data) {
  console.log('Skygear chat event received', data);
});
```

**Comment by chpapa** [comment]
I notice this issue was 5 months ago, may I know if this is still a valid problem? @rickmak @akiroz
