### ISSUE TITLE
Remove `is_direct_message`

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#40]
This attribute is designed to make the one-on-one message special and easy to query. But in various implementation, seem it creates more trouble than its original purpose.

refs: https://github.com/SkygearIO/chat-SDK-Android/issues/1#issuecomment-251927770

Another one from client interview use case: the system needs to do send system message to a one on one conversation. Since all our messages are sent by a `user`, the intuitive way is create a system `user`. And put it into the conversation. Here come the `is_direct_message` creating trouble.

**Comment by royuen** [comment]
Would also need to update JS / iOS / Android SDK

**Comment by kaojohnny** [comment]
- [ ] JS SDK
- [ ] Android SDK
- [ ] iOS SDK
