### ISSUE TITLE
Support Push Notification sending directly

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#42]
This was the lesson learnt after talking with Cloudpillar team who used Skygear Chat.

We should have an option to automatically send push notification to users who receive a new message. Brief idea of the features should be:
## Plugins SDK interface changes
1. On plugins, we shall send a push notification to the receiving devices according to the rules below.
2. Conversations should have a new boolean parameter of _send_push_ (default true)
3. Participants should have a new boolean parameter of _send_push_ (default true); May need a new updateParticipants function.
4. CreateMessage should have a new boolean parameter of _send_push_ (default true)
5. A new function to Enable / Disable all push notification for the user
6. A new callback functions for users to construct the notification message. If this callback function was not set, the default push message is: [[User name]]@[[Conversation Title]]: [[Message]]
7. A function / client side api to set badget count
## Plugins configuration changes
1. Enable (default) or disable all push notification behavior
2. Choose how should the unread badge update (unread message count, unread conversation count, no badge count)

At portal.skygear.io, we wish to have a configuration to disable / enable it, and the badge count choices.

If we do the push message construct function at server side, prefer to have a code editor with the default push message call back code. So people can change things quickly.
## Rules of sending push notification or not

**TODO** Test these rules with new use case to see if it make sense or not.

Run from 1 - 6
1. If push notification was disabled, skip
2. If user disabled all push notification, skip
3. If CreateMessage's send_push is false, skip
4. If Participants's send_push is false, skip
5. If Conversation's send_push is false, skip
6. Send push

**Comment by chpapa** [comment]
For 6, actually is it better to just ask the developer to construct its' push message at client side?

**Comment by rickmak** [comment]
Agree to provide a snippet that demo how to enable sending push notification. With following included:

- Total UnreadCount, Count badge 
- Include conversation title in push message
- Include user attribute in push message

It will kind of `Enable by copy`. i.e. will not include in core cloud code.
