### ISSUE TITLE
`getOrCreateDirectConversation` and `createConversation` return object

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#45]
Seem both are returning `Conversation`. Not `UserConversation` that transientInlucde `User` and `Conversation`.

While the `getConversation` and `getConversations` are returning `UserConversation`, I think it is inconsistence. And the inconsistent introduce bugs and wrapper on project depends on this plugin.

**Comment by rickmak** [comment]
I am referring to JS SDK. Don't know if android and iOS have the same problem.

**Comment by kaojohnny** [comment]
iOS and Android create `Conversation` record directly, so they return `Conversation` instance. And `UserConversation` instance is created in `after_save` of `Conversation` (https://github.com/SkygearIO/chat/blob/master/chat/conversation.py#L58)

**Comment by rickmak** [comment]
Any API in iOS and Android returning `UserConversation` that for listing out of Conversation with Unread count?

**Comment by chpapa** [comment]
Any resolution for this issue?

**Comment by rickmak** [comment]
Agreed to return `UserConversation` and implemented in all SDK.
