### ISSUE TITLE
Planning for API update that satisfy new chat features

### ISSUE THREAD

**Issue by royuen** [SkygearIO/chat#47]
- cross-platform messaging
- Create direct conversations and group chats
- Real time send message & receive message
- Image and media files support
- Unread conversations/messages count
- Manage users in chat groups
- Typing indicators and recipient status
- Push notification

**Comment by chpapa** [comment]
Please beware that besides the obvious features above, there are some more subtle differences need to handle by the API

For example, me and @rickmak once discussed there are two possible way for the plugins to handle chat room, either distinct by conversation topic / chat room, or distinct by participants.

**Comment by rickmak** [comment]
Tentative idea here: https://github.com/rickmak/chat/commit/fcffe54fb1a77a9447154e7f78effcaa108b85e6

Basically:
- get gird of all the `_id`. Try to use Skygear `User` and `Record` as interface.
- get grid of the is_direct_message and change to use `distinctByParticipants`
- get grid of the confusing `Conversation` and `UserConverstion` API.
- add `Receipt`
- add typing indicators by pubsub.

**Comment by chpapa** [comment]
Thanks a lot @rickmak !

I have leave some comments on the commits. And some higher-level questions here:

1. If we want to make it flexible for people to use Skygear Chat with / without Skygear User, shall we include anything on Skygear Chat API? Or shall it be considered separately with Skygear User? (I tends to think it is responsibility of Skygear User to support connecting with a 3rd parties auth provider)
1. Shall we handle push notification with the new API too? Either something like #42, or another simpler design which ask developers to specify how to send the push with an option at createMessage?

**Comment by royuen** [comment]
Overall agree on Ben's comments.

In the new version of chat, is that we would implement the logic in the chat plugin and provide corresponding API to SDKs?

**Comment by rickmak** [comment]
Please checkout https://github.com/rickmak/chat/commit/72a4de2568f9af74113224b96dd72f28d54594e0 and https://github.com/rickmak/chat/commit/639303442082d3fbabd38c3aa7a2612f292469e9

For the update.
