### ISSUE TITLE
Use asset url signer provided by py-skygear

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/chat#72]
After SkygearIO/py-skygear#105, chat plugin can use the asset url signer provided by `py-skgyear`, supporting `s3` and `cloud` asset store.

**Comment by rickmak** [comment]
Current version of asset signer in py-skygear should be good to use.

**Comment by howawong** [comment]
@rickmak  shall we close this?

**Comment by rickmak** [comment]
NO

**Comment by rickmak** [comment]
If people are using cloud deployment with cloud storage, the environment regarding asset prefix is set to `CLOUD_ASSET_PUBLIC_PREFIX` and `CLOUD_ASSET_PRIVATE_PREFIX`. Current get around is to set `ASSET_STORE_URL_PREFIX` to `*.skygeario.com`.
