### ISSUE TITLE
Discussion: Why we have marked delivery functions in SDK?

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#73]
I was draw into attentions of the mark delivery functions in various SDK (and the options to automatically mark delivery in ios SDK) In the process of preparing landing page.

I can understand why do we want developers have the options of automatically mark delivery or not. But in which use case do we need to have a function for setting the delivery status manually?

Would love to learn what you guys think and see if any follow-up message is needed.

Btw, I suggest we should update the API doc so that we explain the relationships between the mark delivery functions and the options / and mention normally this function is not used, if we decided to keep it. @royuen please help create an issue for this if the conversation is concluded?

**Comment by royuen** [comment]
@chpapa 

In iOS SDK, we offer a property to set if you want to mark this as automatically delivered (http://cocoadocs.org/docsets/SKYKitChat/0.0.1/Classes/SKYChatExtension.html#//api/name/automaticallyMarkMessagesAsDelivered). But in JS and Android SDK, we didn't provide this boolean. 

In all 3 SDKs, all messages are marked delivery automatically once another side entered the chat room and see the message.

After discussion, we would like to offer the same functionality as iOS to offer user a chance to do it manually.

Argument to support manually is that if the client application wants to keep it private or have different privacy settings when to mark it delivered, they can do so by turning it to manual send.

See if it makes sense to you? If so will create issue for JS / Android to support automaticallyMarkMessagesAsDelivered attribute.

**Comment by chpapa** [comment]
@royuen Thanks!

I agree that we should have the option to disable the automatic delivery signals -- Actually when I found that on iOS SDK, I think it is a brilliant idea.

But I'm not sure why we need to have a function to let developers set it manually when they disable the automatic one. I just don't have a use case in my head and worried that the mark manually functions are confusing.

If there are use case OR if the team think it is okay to keep it as is, I think we should explain it in BOTH guide and API doc that the mark manual functions are not called normally, and explain the functions relationship with the _automaticallyMarkMessageAsDelivered_ attribute.

So if the team agree we can create issues for JS/Android, and also create an issue to revise the API doc.

Thanks!

**Comment by chpapa** [comment]
Please close this issue after the above issues created and discussion resolved.

**Comment by royuen** [comment]
Following issues are created:

#6 - Revise markDeliveredMessages doc to state relationship with automaticallyMarkMessageAsDelivered
https://github.com/SkygearIO/chat-SDK-JS/issues/6

#9 - Revise markDeliveredMessages doc to state relationship with automaticallyMarkMessageAsDelivered
https://github.com/SkygearIO/chat-SDK-iOS/issues/9

#21 - Revise markDeliveredMessages doc to state relationship with automaticallyMarkMessageAsDelivered
https://github.com/SkygearIO/chat-SDK-Android/issues/21

#5 - Support automaticallyMarkMessageAsDelivered
https://github.com/SkygearIO/chat-SDK-JS/issues/5

#20 - Support automaticallyMarkMessageAsDelivered
https://github.com/SkygearIO/chat-SDK-Android/issues/20
