### ISSUE TITLE
API doc should explain the subscribe method more

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#74]
1. In current JS doc there are no information about the handler, can we add some?

2. It wasn't clear to users (developers) what subscribe functions are available and how to use in the API doc, any thought how we can improve readability?

**Comment by rickmak** [comment]
I tried to address 1 by #4.

For 2, all subscribe function are list at the doc top. I think it it fine for API docs. More can be done in tutorial style. And it is common to put an API tutorial at the class preamble (`SkygearChatContainer provide API access to the chat plugin.` is all be have now). Let do it?

**Comment by chpapa** [comment]
1. Sorry not quite sure how #4 is related with the handler's information (by handler I meant the callback functions signatures for the subscribe functions)

2. I don't understand the English literally "all subscribe function are list at the doc top. I think it it fine for API docs. " => do you meant it already have all subscribe function at the top of doc now or you plan to do it later? And what do the whole sentence meant....? O.o

**Comment by rickmak** [comment]
>  it already have all subscribe function at the top of doc now
