### ISSUE TITLE
Provide method to load the latest message in all conversation user have access to

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#75]
It is a common use-case that developer want to display last message excerpt during the display of list of conversation

**Comment by akiroz** [comment]
I'd want to use this feature in [react-chat-demo](https://github.com/skygear-demo/react-chat-demo), can we prioritize this issue?

**Comment by rickmak** [comment]
This is duplicated with https://github.com/SkygearIO/chat/issues/76

**Comment by rickmak** [comment]
re @akiroz current master have it implemented. chat-SDK-JS also implemented it. Android and iOS is under development.
