### ISSUE TITLE
[Discuss] Efficient way to mark message as read

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/chat#87]
Currently, marking message as read is expected to be done in client code when the messages are fetched. Marking multiple messages as read will involve the following steps:

1. Call lambda `chat:mark_as_read` with the array of messages IDs
2. Create `Receipt` for each message
3. Run `before_save` hook of `Receipt` record to make sure `delivered_at` and `read_at` field won’t be changed once the record is created.
4. Save `Receipt` record via `send_action`
5. Run `after_save` hook of `Receipt` record to update the status of `Message` record and notify the update.

This causes the recurring call between `py-skygear` and `skygear-server`. By marking a number of messages as read, which will be happened when a user enter a conversation, `py-skygear` will be running out of workers and freezes for around half a second.

So, the question is should we have a better way to mark a list of messages as read ?

**Comment by rickmak** [comment]
related: https://github.com/SkygearIO/chat-SDK-JS/issues/22

**Comment by howawong** [comment]
In #112,
The  improved flow is as follow

1.  Fetch messages by `Message.fetch`
2. Fetch receipts by `Receipt.fetch`
3.  Upsert receipts if  at least one of `deliver_at` and `read_at` is updated.
4.  `updateMessageStatus` and `notifyParticipants` for each message in step 3

No more back and forth by before_save and after_save hooks.
