### ISSUE TITLE
Support updateMessage() and deleteMessage()

### ISSUE THREAD

**Issue by david90** [SkygearIO/chat#92]
Meanwhile we suggested users to update / delete messages as typical record, but actually message is not editable.
```
Failed to save message: message is not editable
                                                                    io.skygear.skygear.Error: message is not editable
 ```

So a more proper fix is introducing `updateMessage` and `deleteMessage` in the chat container.

**Comment by ben181231** [comment]
Currently, the message is ensure not editable via before save hook.

Ref. https://github.com/SkygearIO/chat/blob/5eb6a79/chat/message_handlers.py#L111

**Comment by rickmak** [comment]
In merge c504e56, the `message_history` does not properly behave.

Step to reproduce:

1. Save a message with `One`
1. Edit the message to `Two`
1. In DB, the `message_history` hold the value `Two`. `message` hold the value `Two`

Expected behavour:
In DB, the `message_history` hold the value `Onw`. `message` hold the value `Two`

**Comment by rickmak** [comment]
On message deleted, the pubsub event is `update` not `delete`
