### ISSUE TITLE
[Discuss] Update the column names in the Message and Receipt table

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/chat#94]
In the receipt table, there are 2 references. One is user_id and one is message_id. 

As it is a reference, if I want to get the user id of the user, one has to write user_id.id. It is kinda confusing.

Besides, in the message table, the attribute says "conversation_status". But in fact, it should mean the status of the mesage.

So these are the updates I propose:

**Message**
conversation_status -> message_status
conversation_id -> conversation

**Receipt**
user_id -> user
message_id -> message

**Comment by rickmak** [comment]
Is @chpapa think rename and introduce backward incompatible is okay?

**Comment by chpapa** [comment]
@rickmak this one seems serious enough that as we don't have many users now (who's using this version of chat plugins in production?) I think is okay.
