### ISSUE TITLE
Create editedAt and editedBy attributes

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat#97]
Conclusion:

1. Add new attribute:
    - `editedAt` - prefilled with `createdAt`
    - `editedBy` - null if not edited
1. `updateMessage` at #92 should update both attributes.
1. Make `getMessages` have a new attribute to choose sort by `_created_at` or `editedAt` (default by `created_at`)

**Comment by samuelplaymore** [comment]
I understand that message cannot be edited now. 
However, it may be a new feature.

I suggest `markAsDelivered` and `markAsRead` don't need to update the `updatedAt` and `updatedBy`, because it may not be a use case (To check when it mark as read ? we should check in the `receipt` table, if I am correct). 

If we allow user to edit the message, this is hard to check when the message is edited.
`updatedAt` is not correct, because it may be overwritten by `markAsRead` / `markAsDelivered`.

Or we need to add two more field : `editedAt` and `editedBy`

**Comment by cheungpat** [comment]
> Or we need to add two more field : editedAt and editedBy

I would suggest we have this.

**Comment by chpapa** [comment]
But even with editedAt / editedBy, maybe we should still review is markAsDelivered / markAsRead updating Message's updatedAt / updatedBy make sense? Sounds surprising.

**Comment by cheungpat** [comment]
@chpapa `message` has a `conversation_status` field which is updated with a new conversation status when marking delivery/read status. In skygear record database, `_updated_at` is always updated with the current time when the record is updated.

**Comment by rickmak** [comment]
As long as it based on skygear core record API, the _update_at will always update to when the message is changed, edited or conversation_status changes.

What makes @chpapa think is it surprising, I guess is you don't think markAsRead is an update to message state. It is a state change of message in the current implementation.

**Comment by samuelplaymore** [comment]
I understand it change the field `conversation_status`. and therefore will update the `updatedAt`.
However, I notice that `markAsRead` and `markAsDelivered` are both lambda function.
It imply we can use `DB.pool.connect` and edit the record directly, to avoid edit the `updateAt`. 

By the way, about `conversation_status`. It is not correct or I use it wrongly??
I create a Individual Chat (2 member only).
And I create some message, and mark it as read.
In DB, I saw 22 records in `message` table, and 44 records in `receipt` table.
However, records in `message` table are still in `some_read` / `delivered` / `all_read` status.
I didn't look deep to find the reason. Maybe I will if I have time.

flow:
1. createMessage,
2. markAsDelivered when receive it from pubsub / by `getMessage`
3. if in a chatroom,
- get the `last_read_message` and query all unread messages by greater than this `last_read_message`
- mark the latest unread messages with `markAsLastMessageRead`
- mark all unread message with `markAsRead`

any comment on this flow? thanks :)

**Comment by chpapa** [comment]
> What makes @chpapa think is it surprising, I guess is you don't think markAsRead is an update to message state. It is a state change of message in the current implementation.

@rickmak @cheungpat in retrospect what makes me surprise is I was thinking in terms of Chat App's knowledge domains, so message receipt status shouldn't change `_updated_at`; But when I think in terms of CloudDB domain, it becomes very clear.

So I think ideally, the design change here could be: move the receipt status away from the message record so the CloudDB knowledge domains won't conflict with Chat knowledge domain.

Less ideal is add `_edited_at` and `_edited_by`, hopefully, people would understand better by looking closely in the API docs/guides.

**Comment by samuelplaymore** [comment]
> So I think ideally, the design change here could be: move the receipt status away from the message record so the CloudDB knowledge domains won't conflict with Chat knowledge domain.

As I know, It is already doing this. `receipt` table save the receipt status. 
So, according to your idea, we may just remove the field `conversation_status`.

**Comment by chpapa** [comment]
What do you think @rickmak? I guess if we denormalize the status from receipt table there are some reason?

**Comment by rickmak** [comment]
Mainly the performance reason. To enable a fast query of messages without join.

**Comment by chpapa** [comment]
@rickmak in that case, shall we:

1. add `editedAt` and `editedBy` columns for messages
1. add `editMessage` function in chat SDK? which will update the two columns.

What do you think @samuelplaymore ?

**Comment by samuelplaymore** [comment]
> add editedAt and editedBy columns for messages
add editMessage function in chat SDK? which will update the two columns.

Sound good. So, in client side, they should write code like:

`
messages.forEach(m => m.displayDate = m.editedAt || m.createdAt);
messages.sort((a,b)=> a.displayDate - b.displayDate)
`

for displaying the message with meaningful order

**Comment by chpapa** [comment]
or if we have `editedAt`, shall we have an option at `getMessages` for people to choose if they want to return the result sorted by `createdAt` and `editedAt`? (default `createdAt`)

**Comment by samuelplaymore** [comment]
> or if we have editedAt, shall we have an option at getMessages for people to choose if they want to return the result sorted by createdAt and editedAt? (default createdAt)

sure, but let me remind that: sometime, we need to sort by both `createdAt` and `editedAt`.

Use case :
messages order by `createdAt` in most case; but if a message be edited, it need to pop to the top.
moreover, we want to show when the message is edited.

Screen like:

msg001 @ 12:01
msg003 @ 12:02
msg004 @ 12:03
editMsg002 - edited @ 12:04
msg005 @ 12:05
msg006 @ 12:06

**Comment by chpapa** [comment]
@samuelplaymore I guess as long as we have `editedAt` prefilled with `createdAt` value when it was first created (instead of null), your use case would be fulfilled?

**Comment by samuelplaymore** [comment]
> @samuelplaymore I guess as long as we have editedAt prefilled with createdAt value when it was first created (instead of null), your use case would be fulfilled?

Um... I considered this, but I think it may not be good approach.
We can not know which message is edited or not.
(OR we need to check `createdAt` != `editedAt` || `editedBy === null`).
This is leading to misunderstanding, for other developers.

**Comment by chpapa** [comment]
> (OR we need to check createdAt != editedAt || editedBy === null

So the trade-off is either we want the developer to check by `createdAt != editedAt`, or lose the ability to sort by `editedAt` directly. In that case, I guess require developers to check `createdAt != editedAt` is easier / more trivial? @samuelplaymore ?

**Comment by samuelplaymore** [comment]
I think both is okay. :)
So, remember to document it carefully, to avoid misunderstanding.

**Comment by chpapa** [comment]
I'm updating this issue description with the conclusion here, to make developer easier to start working on this:

1. Add new attribute:
    - `editedAt` - prefilled with `createdAt`
    - `editedBy` - null if not edited
1. `updateMessage` at #92 should update both attributes.
1. Make `getMessages` have a new attribute to choose sort by `_created_at` or `editedAt` (default by `created_at`)

**Comment by howawong** [comment]
All platforms implementations are done. Closing this issue.
